{% set version = '2.0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vegclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vegclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vegclust/vegclust_{{ version }}.tar.gz
  sha256: dd028abd8fd87f7ae264731046b83a210a98eee3c9ef694eec4dc3a51e8e61a3

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-vegan
  run:
    - r-base
    - r-vegan

test:
  commands:
    - $R -e "library('vegclust')"           # [not win]
    - "\"%R%\" -e \"library('vegclust')\""  # [win]

about:
  home: https://emf-creaf.github.io/vegclust/
  license: GPL-2.0-or-later
  summary: 'A set of functions to: (1) perform fuzzy clustering of vegetation data (De Caceres
    et al, 2010) <doi:10.1111/j.1654-1103.2010.01211.x>; (2) to assess ecological community
    similarity on the basis of structure and composition (De Caceres et al, 2013) <doi:10.1111/2041-210X.12116>.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
